"""empty message

Revision ID: 323912af6e48
Revises: e6ccd316ba19
Create Date: 2021-07-24 10:30:08.019394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323912af6e48'
down_revision = 'e6ccd316ba19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('pax', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('event'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pax'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventform')
    # ### end Alembic commands ###
