"""empty message

Revision ID: 42169c6212eb
Revises: d6e9b2d48cc0
Create Date: 2021-07-09 10:34:06.400635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42169c6212eb'
down_revision = 'd6e9b2d48cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'adress')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('adress', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
