"""empty message

Revision ID: 57056dd6a956
Revises: c24a3dac17d2
Create Date: 2021-08-30 19:15:42.540874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57056dd6a956'
down_revision = 'c24a3dac17d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventform',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('pax', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='eventform_pkey'),
    sa.UniqueConstraint('date', name='eventform_date_key'),
    sa.UniqueConstraint('email', name='eventform_email_key'),
    sa.UniqueConstraint('event', name='eventform_event_key'),
    sa.UniqueConstraint('id', name='eventform_id_key'),
    sa.UniqueConstraint('name', name='eventform_name_key'),
    sa.UniqueConstraint('pax', name='eventform_pax_key'),
    sa.UniqueConstraint('phone', name='eventform_phone_key')
    )
    # ### end Alembic commands ###
