"""empty message

Revision ID: 84744b93cc43
Revises: b9a2c5c6657a
Create Date: 2021-07-09 11:11:15.308100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84744b93cc43'
down_revision = 'b9a2c5c6657a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('adress', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'city')
    op.drop_column('user', 'adress')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
