"""empty message

Revision ID: ac545bc5a7d3
Revises: 57056dd6a956
Create Date: 2021-09-13 09:49:58.442123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac545bc5a7d3'
down_revision = '57056dd6a956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('googleuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('familyName', sa.String(length=80), nullable=False),
    sa.Column('givenName', sa.String(length=80), nullable=False),
    sa.Column('googleId', sa.String(length=8000), nullable=False),
    sa.Column('tokenId', sa.String(length=8000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('googleId'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tokenId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('googleuser')
    # ### end Alembic commands ###
