"""empty message

Revision ID: b9a2c5c6657a
Revises: 42169c6212eb
Create Date: 2021-07-09 10:40:38.771634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a2c5c6657a'
down_revision = '42169c6212eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_category_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_category_key', 'products', ['category'])
    # ### end Alembic commands ###
