"""empty message

Revision ID: d6179fe5a680
Revises: e1d1648ce99c
Create Date: 2021-07-13 09:47:18.080619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6179fe5a680'
down_revision = 'e1d1648ce99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'user', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
