"""empty message

Revision ID: e64d8522a368
Revises: 
Create Date: 2021-07-08 13:22:17.978820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64d8522a368'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cakes',
    sa.Column('id_cakes', sa.Integer(), nullable=False),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_cakes'),
    sa.UniqueConstraint('id_cakes'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gifts',
    sa.Column('id_gifts', sa.Integer(), nullable=False),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_gifts'),
    sa.UniqueConstraint('id_gifts'),
    sa.UniqueConstraint('name')
    )
    op.create_table('glazed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('testclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('treats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('adress', sa.String(length=250), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('treats')
    op.drop_table('testclass')
    op.drop_table('glazed')
    op.drop_table('gifts')
    op.drop_table('cakes')
    # ### end Alembic commands ###
